#!/system/bin/sh
#
# Script to start "" on the device, which has a very rudimentary
# shell.
#
export CLASSPATH=/system/framework/factory.jar
exec app_process /system/bin com.android.commands.factory.Factory "$@"


